### PR TITLE
Update PROJECT_GOVERNANCE.md and RELEASE.md: A few textual improvements

### PR DESCRIPTION
**Pull request by Jonasvdbo**
I made a few small textual improvements to the project_goverance.md and release.md files.

Signed-off-by: Jonas van den Bogaard <3628277+Jonasvdbo@users.noreply.github.com>

### CODE REVIEW

**Comment by TonyXiang8787** [comment]
@Jonasvdbo can you make one PR for the changes of both files?

**Comment by Jonasvdbo** [comment]
> @Jonasvdbo can you make one PR for the changes of both files?

Sure!

**Comment by Jonasvdbo** [comment]
The https://github.com/alliander-opensource/power-grid-model/pull/176 is merged is this PR.

**Comment by Jonasvdbo** [comment]
The PR is ready for review.

**Review by TonyXiang8787 — APPROVED** [review]

**Pull request merged**
