### PR TITLE
sonar cloud for python

### PR DESCRIPTION
**Pull request by TonyXiang8787**

### CODE REVIEW

**Comment by TonyXiang8787** [comment]
@Jonasvdbo Please have a look. It only checks Python files without coverage due to compiled issue.

**Comment by Jonasvdbo** [comment]
@TonyXiang8787 Good that works for python files! Altough my understanding was that Sonarcloud also was able to Analyze C++ Pull request. Let me look into that. 

Btw if you want too, you can also included sonarcloud badge in your readme.me. See https://sonarcloud.io/project/overview?id=alliander-opensource_Weather-Provider-API for an example.

**Comment by TonyXiang8787** [comment]
@Jonasvdbo the C++ check is very intrusive.

**Comment by Jonasvdbo** [comment]
@TonyXiang8787 For my understanding, what makes the C++ check very intrusive?

**Comment by Jonasvdbo** [comment]
@TonyXiang8787 A suggestion for my side, let's just start using Sonarcloud for python only and let's look into using Sonarcloud for C++ too at a later moment in time. Personally, I believe SonarCloud can also help us in the area of C++ but that may require a bit more research and configuration.

**Review by Jonasvdbo — APPROVED** [review]
For now let's just start using Sonarcloud for python only and let's look into using Sonarcloud for C++ too at a later moment in time. Personally, I believe SonarCloud can also help us in the area of C++ but that may require a bit more research and discussion first. I updated the title of the PR to "Sonar cloud for python" from "Sonar cloud" to make this more clear.

**Comment by Jonasvdbo** [comment]
@TonyXiang8787 Only thing I forgot to mention in my review comments, please don't forgot to sign off you commit with "Signed-off-by: Joe Smith <joe.smith@email.com>". For more information see the "Signing the Developer Certificate of Origin (DCO)" in https://github.com/alliander-opensource/power-grid-model/blob/main/CONTRIBUTING.md

**Pull request merged**
